### ISSUE TITLE
SSL_ERROR_UNRECOGNIZED_NAME_ALERT

### ISSUE THREAD

**Issue by KOLANICH** [phikal/REDB#4]
>An error occurred during a connection to redb.org.uk. SSL peer has no certificate for the requested DNS name. Error code: SSL_ERROR_UNRECOGNIZED_NAME_ALERT

**Comment by phikal** [comment]
That's actually a lighttpd error, and not related to the server itself, so I'm going to close the issue.

But, don't worry, I'm working on it.

**Comment by phikal** [comment]
Looks like it works now:

>![screenshot at 2017-02-20 19 14 26](https://cloud.githubusercontent.com/assets/6370419/23137185/e7991b4c-f7a0-11e6-9898-6427aef2a023.png)
